### ISSUE TITLE
Actual hold events differs from IHold interface

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MRDesignLabs_Unity_Tools#21]
The interaction manager sends `HoldStarted`, `HoldCompleted` or `HoldCanceled` while the interface defines `OnHoldStarted`, `OnHoldCompleted` `OnHoldCanceled`

https://github.com/Microsoft/MRDesignLabs_Unity_Tools/blob/a129550db5cd215cbc819ac205c29a5e642934f8/HUX/Scripts/Interaction/InteractionManager.cs#L628
https://github.com/Microsoft/MRDesignLabs_Unity_Tools/blob/a129550db5cd215cbc819ac205c29a5e642934f8/HUX/Scripts/Interaction/InteractionManager.cs#L659
https://github.com/Microsoft/MRDesignLabs_Unity_Tools/blob/a129550db5cd215cbc819ac205c29a5e642934f8/HUX/Scripts/Interaction/InteractionManager.cs#L692
https://github.com/Microsoft/MRDesignLabs_Unity_Tools/blob/01755e154891b55f21a503927fa35ea69e1cc914/HUX/Scripts/Interaction/Interfaces/IHold.cs#L11-L27

**Comment by paseb** [comment]
@Zod- 

You are look at two ways of getting events that are separate from each other.  One is using an interface for a component and gets direct callbacks (more efficient and not relying on sendmessage).  And the other is using send message where it does not require an interface and can be used for rapid prototyping.

The reason why we provide both is for people that just want to write a component and not necessarily extend from a number of interfaces to just get the direct message event aka the function signatures that don't have [On]HoldStarted.  The interface OnHold functions are the correct ones that are called directly from InteractionManager.  Those events are fired off directly after the lines you noted.
SendEvent(OnHoldStarted, focusObject, eventArgs);

This is intentional to provide easy methods for rapid prototyping however the proper or more efficient way would be to use the interface with the direct callbacks.

thanks,
-pat

**Comment by Zod-** [comment]
How are you supossed to use the interface? I'm not getting any events when I implement them. Also `SendEvent` just calls the actions that have been manually assigned to the `InteractionManager` but not the interface. They also have a different signature as the interface so I can't even assign them myself with the interface. 
The interface isn't really used anywhere in the codebase except for on the `ScrollableContent`.

**Comment by paseb** [comment]
@Zod- Ah I'm sorry, you are correct.  We are in the process of merging input systems with MRTK and should have that by the end of next week.  The interfaces were not fully implemented in MRDL and the 2 methods for getting interactions are:

1.  Extend Button or InteractibleObject to override or implement the correct callback signature
2. Just have a component with the SendMessage function signature (HoldStarted ...etc).   

I could have InteractibleObject and InteractionManager use updated interfaces but since I'm removing our input routing to merge with MRTK it wouldn't make a lot of sense.

Sorry for the confusion.

thanks,
-pat
